---
- name: Provisioning local machine
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Install packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - nginx
      - php7.0
      - php-mysql

  - name: Clone wordpress repo
    git:
      repo: "https://github.com/WordPress/WordPress.git"
      dest: /var/www/wordpress/
      version: master

  - name: Copy nginx.conf
    copy:
      src: nginx.conf
      dest: /etc/nginx/sites-enabled/default

  - name: Enable service php-fpm
    service:
      name: php7.0-fpm
      enabled: yes
      state: started

  - name: Enable service nginx
    service:
      name: nginx
      enabled: yes
      state: restarted
